apiVersion: v2
name: xml-to-json-list-template
description: Chart for an Argo template that will run the XML-to-JSON-list tool
type: application
# NOTE: This is auto-updated by sbt on releases.
version: 0.0.0
